/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bmi_checker;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Code extends javax.swing.JFrame {

    /**
     * Creates new form Code
     */
    public Code() {
        initComponents();
        setOpacity((float)0.95);
    }

    private int x = 0,  y = 0;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        calculationpnl = new javax.swing.JPanel();
        exit = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtweight = new javax.swing.JTextField();
        txtfeet = new javax.swing.JTextField();
        txtinches = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        calculatebMi = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtresult = new javax.swing.JTextField();
        txtage = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        agewarning = new javax.swing.JLabel();
        weightwarning = new javax.swing.JLabel();
        heightwarning = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(61, 61, 92));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        calculationpnl.setBackground(new java.awt.Color(0, 0, 0));
        calculationpnl.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                calculationpnlMouseDragged(evt);
            }
        });
        calculationpnl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                calculationpnlMousePressed(evt);
            }
        });

        exit.setBackground(new java.awt.Color(0, 0, 0));
        exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/multiple.png"))); // NOI18N
        exit.setOpaque(true);
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
        });

        minimize.setBackground(new java.awt.Color(0, 0, 0));
        minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/minus.png"))); // NOI18N
        minimize.setOpaque(true);
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeMouseExited(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("BMI Calculator");

        javax.swing.GroupLayout calculationpnlLayout = new javax.swing.GroupLayout(calculationpnl);
        calculationpnl.setLayout(calculationpnlLayout);
        calculationpnlLayout.setHorizontalGroup(
            calculationpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, calculationpnlLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        calculationpnlLayout.setVerticalGroup(
            calculationpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(calculationpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(minimize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, calculationpnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        jScrollPane1.setBorder(null);

        jTable1.setBackground(new java.awt.Color(61, 61, 92));
        jTable1.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"19-24", "19-24"},
                {"25-34", "20-25"},
                {"35-44", "21-26"},
                {"45-54", "22-27"},
                {"55-64", "23-28"},
                {"Above 65", "24-29"}
            },
            new String [] {
                "Age", "BMI"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
        }

        jScrollPane2.setBorder(null);

        jTable2.setBackground(new java.awt.Color(61, 61, 92));
        jTable2.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        jTable2.setForeground(new java.awt.Color(255, 255, 255));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Normal Weight", "18.5-24.9"},
                {"Overweight", "25-29.9"},
                {"Obesity level I", "30-34.9"},
                {"Obesity level II", "35-39.9"},
                {"Obesity level III", "Above 40"}
            },
            new String [] {
                "Meaning", "BMI"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setGridColor(new java.awt.Color(204, 204, 204));
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
            jTable2.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BMI Table");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("BMI Table NCI");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Weight");

        txtweight.setBackground(new java.awt.Color(61, 61, 92));
        txtweight.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 24)); // NOI18N
        txtweight.setForeground(new java.awt.Color(255, 255, 255));
        txtweight.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txtweight.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtweightKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtweightKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtweightKeyTyped(evt);
            }
        });

        txtfeet.setBackground(new java.awt.Color(61, 61, 92));
        txtfeet.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 24)); // NOI18N
        txtfeet.setForeground(new java.awt.Color(153, 153, 153));
        txtfeet.setText("Feet");
        txtfeet.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txtfeet.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtfeetFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtfeetFocusLost(evt);
            }
        });
        txtfeet.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtfeetKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfeetKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfeetKeyTyped(evt);
            }
        });

        txtinches.setBackground(new java.awt.Color(61, 61, 92));
        txtinches.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 24)); // NOI18N
        txtinches.setForeground(new java.awt.Color(153, 153, 153));
        txtinches.setText("Inches");
        txtinches.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txtinches.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtinchesFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtinchesFocusLost(evt);
            }
        });
        txtinches.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtinchesKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtinchesKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtinchesKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Height       ");

        calculatebMi.setBackground(new java.awt.Color(61, 61, 92));
        calculatebMi.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        calculatebMi.setForeground(new java.awt.Color(255, 255, 255));
        calculatebMi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        calculatebMi.setText("Calculate");
        calculatebMi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        calculatebMi.setOpaque(true);
        calculatebMi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calculatebMiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                calculatebMiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                calculatebMiMouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("B M I");

        txtresult.setEditable(false);
        txtresult.setBackground(new java.awt.Color(61, 61, 92));
        txtresult.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 24)); // NOI18N
        txtresult.setForeground(new java.awt.Color(255, 255, 255));
        txtresult.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtresult.setBorder(null);
        txtresult.setOpaque(false);

        txtage.setBackground(new java.awt.Color(61, 61, 92));
        txtage.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 24)); // NOI18N
        txtage.setForeground(new java.awt.Color(255, 255, 255));
        txtage.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txtage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtageKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtageKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtageKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Age");

        status.setBackground(new java.awt.Color(61, 61, 92));
        status.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        status.setForeground(new java.awt.Color(255, 255, 255));

        agewarning.setBackground(new java.awt.Color(61, 61, 92));
        agewarning.setForeground(new java.awt.Color(61, 61, 92));
        agewarning.setText("Please enter digit");

        weightwarning.setBackground(new java.awt.Color(61, 61, 92));
        weightwarning.setForeground(new java.awt.Color(61, 61, 92));
        weightwarning.setText("Please enter digit");

        heightwarning.setBackground(new java.awt.Color(61, 61, 92));
        heightwarning.setForeground(new java.awt.Color(61, 61, 92));
        heightwarning.setText("Please enter digit");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(calculationpnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(102, 102, 102)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(status)
                            .addComponent(txtresult, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(txtfeet, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtinches, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(heightwarning, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(8, 8, 8)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(weightwarning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(txtweight, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(agewarning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtage, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE))
                                        .addGap(40, 40, 40)))
                                .addGap(72, 72, 72))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(calculatebMi, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(calculationpnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(agewarning)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(txtweight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(weightwarning)
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtfeet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtinches, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(heightwarning)
                                .addGap(30, 30, 30)
                                .addComponent(calculatebMi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtresult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addComponent(status)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(783, 423));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:
        
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
        // TODO add your handling code here:
        exit.setBackground(Color.red);
    }//GEN-LAST:event_exitMouseEntered

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
        // TODO add your handling code here:
        exit.setBackground(Color.black);
    }//GEN-LAST:event_exitMouseExited

    private void minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseEntered
        // TODO add your handling code here:
        minimize.setBackground(new Color(89, 89, 89));
    }//GEN-LAST:event_minimizeMouseEntered

    private void minimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseExited
        // TODO add your handling code here:
        minimize.setBackground(Color.black);
    }//GEN-LAST:event_minimizeMouseExited

    private void calculatebMiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calculatebMiMouseClicked
        // TODO add your handling code here:
        calculatebmi();
    }//GEN-LAST:event_calculatebMiMouseClicked

    private void txtfeetFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfeetFocusGained
        // TODO add your handling code here:
        if(txtfeet.getText().equals("Feet"))
        {
            txtfeet.setText(null);
        }
        
    }//GEN-LAST:event_txtfeetFocusGained

    private void txtinchesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtinchesFocusGained
        // TODO add your handling code here:
        if(txtinches.getText().equals("Inches"))
        {
            txtinches.setText(null);
        }
       
    }//GEN-LAST:event_txtinchesFocusGained

    private void txtinchesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtinchesFocusLost
        // TODO add your handling code here:
        if(txtinches.getText().equals(""))
        {
            txtinches.setForeground(new Color(153,153,153));
            txtinches.setText("Inches");
        }
    }//GEN-LAST:event_txtinchesFocusLost

    private void txtfeetFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfeetFocusLost
        // TODO add your handling code here:
        if(txtfeet.getText().equals(""))
        {
            txtfeet.setForeground(new Color(153,153,153));
            txtfeet.setText("Feet");
        }
        
    }//GEN-LAST:event_txtfeetFocusLost

    private void txtageKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtageKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_DOWN)
        {
            txtweight.requestFocus();
        }
    }//GEN-LAST:event_txtageKeyPressed

    private void txtweightKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtweightKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_DOWN)
        {
            txtfeet.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_UP)
        {
            txtage.requestFocus();
        }
    }//GEN-LAST:event_txtweightKeyPressed

    private void txtfeetKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfeetKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_RIGHT)
        {
            txtinches.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_DOWN)
        {
            txtweight.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            calculatebmi();
        }
    }//GEN-LAST:event_txtfeetKeyPressed

    private void txtinchesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtinchesKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_LEFT)
        {
            txtfeet.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_UP)
        {
            txtweight.requestFocus();
        }
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            calculatebMi.setBackground(Color.white);
            calculatebMi.setForeground(new Color(61,61,92));
            calculatebmi();    
        }
    }//GEN-LAST:event_txtinchesKeyPressed

    private void calculatebMiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calculatebMiMouseEntered
        // TODO add your handling code here:
        calculatebMi.setBackground(Color.white);
        calculatebMi.setForeground(new Color(61,61,92));
    }//GEN-LAST:event_calculatebMiMouseEntered

    private void calculatebMiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calculatebMiMouseExited
        // TODO add your handling code here:
        calculatebMi.setBackground(new Color(61,61,92));
        calculatebMi.setForeground(Color.white);
    }//GEN-LAST:event_calculatebMiMouseExited

    private void calculationpnlMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calculationpnlMousePressed
        // TODO add your handling code here:
        
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_calculationpnlMousePressed

    private void calculationpnlMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calculationpnlMouseDragged
        // TODO add your handling code here:
        this.setLocation(evt.getXOnScreen() - x, evt.getYOnScreen() - y);
    }//GEN-LAST:event_calculationpnlMouseDragged

    private void txtageKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtageKeyTyped
        // TODO add your handling code here:
        char number = evt.getKeyChar();
        if(Character.isAlphabetic(number))
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtageKeyTyped

    private void txtweightKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtweightKeyTyped
        // TODO add your handling code here:
         char number = evt.getKeyChar();
        if(Character.isAlphabetic(number))
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtweightKeyTyped

    private void txtfeetKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfeetKeyTyped
        // TODO add your handling code here:
         char number = evt.getKeyChar();
        if(Character.isAlphabetic(number))
        {
            evt.consume();
        }
        
        txtfeet.setForeground(Color.white);
        
    }//GEN-LAST:event_txtfeetKeyTyped

    private void txtinchesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtinchesKeyTyped
        // TODO add your handling code here:
         char number = evt.getKeyChar();
        if(Character.isAlphabetic(number))
        {
            evt.consume();
        }
        
        txtinches.setForeground(Color.white);
    }//GEN-LAST:event_txtinchesKeyTyped

    private void txtageKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtageKeyReleased
        // TODO add your handling code here:
        char string = evt.getKeyChar();
        if(Character.isAlphabetic(string))
        {
            agewarning.setForeground(Color.red);
        }
        else 
        {
            agewarning.setForeground(new Color(61,61,92));
        }
    }//GEN-LAST:event_txtageKeyReleased

    private void txtweightKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtweightKeyReleased
        // TODO add your handling code here:
         char string = evt.getKeyChar();
        if(Character.isAlphabetic(string))
        {
            weightwarning.setForeground(Color.red);
        }
        else 
        {
            weightwarning.setForeground(new Color(61,61,92));
        }
    }//GEN-LAST:event_txtweightKeyReleased

    private void txtfeetKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfeetKeyReleased
        // TODO add your handling code here:
         char string = evt.getKeyChar();
        if(Character.isAlphabetic(string))
        {
            heightwarning.setForeground(Color.red);
        }
        else 
        {
            heightwarning.setForeground(new Color(61,61,92));
        }
    }//GEN-LAST:event_txtfeetKeyReleased

    private void txtinchesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtinchesKeyReleased
        // TODO add your handling code here:
         char string = evt.getKeyChar();
        if(Character.isAlphabetic(string))
        {
            heightwarning.setForeground(Color.red);
        }
        else 
        {
            heightwarning.setForeground(new Color(61,61,92));
        }
    }//GEN-LAST:event_txtinchesKeyReleased

    
    private void calculatebmi()
    {
        
        if(txtweight.getText().equals("") || txtage.getText().equals("") || txtfeet.getText().equals("Feet") || txtinches.getText().equals("Inches"))
        {
            JOptionPane.showMessageDialog(null, "Please give input", "Null field", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            
        
        double weight = Double.parseDouble(txtweight.getText());
        
        double feet = Double.parseDouble(txtfeet.getText()); 
        
        double inches = Double.parseDouble(txtinches.getText());
        
        double finalweight = (feet*.3048) + (inches*.0254);
        
        double bmi = weight /  (finalweight*finalweight);
        
        DecimalFormat decimalformat = new DecimalFormat("#.00");
        
        int age = Integer.parseInt(txtage.getText());
        
        txtresult.setText(String.valueOf(decimalformat.format(bmi)));
        
        
         if (bmi<=16)
         {
            status.setText("Very Severely Underweight");
            txtresult.setBackground(Color.blue);
         }
   
        else if (bmi>16&&bmi<=17)
        {
            status.setText("Severely Underweight");
            txtresult.setBackground(Color.blue);
        }

        else if (bmi>17&&bmi<=18.5)
        {
            status.setText("Underweight");
            txtresult.setBackground(Color.blue);
        }
        
        else if (bmi>18.5&&bmi<=25)
        {
            status.setText("Normal");
            txtresult.setBackground(Color.green);
        }
      
        else if (bmi>25&&bmi<=30)
        {
            status.setText("Overweight");
            txtresult.setBackground(Color.red);
        }

        else if (bmi>30&&bmi<=35)
        {
            status.setText("Obeseity Level I");
            txtresult.setBackground(Color.red);
        }

        else if (bmi>35&&bmi<=40)
        {
            status.setText("Obesity Level II");
            txtresult.setBackground(Color.red);
        }

        else if (bmi>40)
        {
            status.setText("Obesity Level III");
            txtresult.setBackground(Color.red);
        }
         
     }
        

    }
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Code.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Code.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Code.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Code.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Code().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agewarning;
    private javax.swing.JLabel calculatebMi;
    private javax.swing.JPanel calculationpnl;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel heightwarning;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel minimize;
    private javax.swing.JLabel status;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextField txtfeet;
    private javax.swing.JTextField txtinches;
    private javax.swing.JTextField txtresult;
    private javax.swing.JTextField txtweight;
    private javax.swing.JLabel weightwarning;
    // End of variables declaration//GEN-END:variables
}
